# Generated by Django 5.1.2 on 2024-11-29 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosEsteticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre_servicio', models.CharField(default='1', max_length=100, verbose_name='Nombre del Servicio')),
                ('_descripcion', models.CharField(default='1', max_length=100, verbose_name='Descripción')),
                ('_duracion', models.CharField(default='1', max_length=50, verbose_name='Duración')),
                ('_precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoCorporal',
            fields=[
                ('serviciosesteticos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CrudServiciosEsteticos.serviciosesteticos')),
                ('_zona_tratada', models.CharField(max_length=100, verbose_name='Zona Tratada')),
                ('_tipo_producto', models.CharField(max_length=100, verbose_name='Tipo de Producto')),
            ],
            bases=('CrudServiciosEsteticos.serviciosesteticos',),
        ),
        migrations.CreateModel(
            name='TratamientoFacial',
            fields=[
                ('serviciosesteticos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CrudServiciosEsteticos.serviciosesteticos')),
                ('_tipo_tratamiento', models.CharField(max_length=100, verbose_name='Tipo de Tratamiento')),
                ('_tipo_piel', models.CharField(max_length=100, verbose_name='Tipo de Piel')),
            ],
            bases=('CrudServiciosEsteticos.serviciosesteticos',),
        ),
    ]
